### ISSUE TITLE
Make protocol available as part of url for ES

### ISSUE THREAD

**Issue by ruflin** [elastic/libbeat#133]
Currently to set up https with the following config is needed:

```
output:
  elasticsearch:
    enabled: true
    hosts: ["admin:test@found.io:9243"]
    protocol: https
```

In the other elasticsearch clients, the full url can be directly used without having to specify the protocol separately:

```
output:
  elasticsearch:
    enabled: true
    hosts: ["https://admin:test@found.io:9243"]
```

We should support this in the same way. This will also make it easy to mix multiple hosts and even have different protocols.
