### ISSUE TITLE
Windows. The service process could not connect to the service controller.

### ISSUE THREAD

**Issue by dmitriyett** [elastic/libbeat#227]
I'm using filebeat as a log shipper and every time I am starting filebeat instance I'm receiving following error in console:

```
service_windows.go:45: ERR Error: The service process could not connect to the service controller.
```

I'm using 1.0.0-beta4 filebeat for windows.

My logstash.conf file:

```
input {
    beats {
        port => 5044
    }
}

output {
    stdout {}
}
```

My filebeat.yml file:

```
filebeat:
  prospectors:
    -
      paths:
        - "D:\\Repositories\\logstashtests\\logs.txt"
      type: log
output:
  logstash:
    enabled: true

    hosts: ["127.0.0.1:5044"]
```

For more information you can go to elastic/filebeat#145
