### ISSUE TITLE
Debian logging to file fails if path not configured

### ISSUE THREAD

**Issue by urso** [elastic/libbeat#275]
Initialization of file logger fails (tested on debian 8) if no path is configured.

On linux default path is /var/log/<beatname>, but startup fails if logging.files.path is not configured:

    # filebeat -c /etc/filebeat/filebeat.yml
    Error initializing logging: mkdir : no such file or directory

Setting path to default value (/var/log/<beatname> ) in config file resolves problem and directory is generated.

**Comment by ruflin** [comment]
@urso @andrewkroh I suggest we fix this directly in combiation with: https://github.com/elastic/libbeat/issues/264

The problem about the default path is that it is system dependent so I don't think it should be in the code. Probably if no path is defined, we should also throw an error message instead of the above.

**Comment by ruflin** [comment]
@urso What was your exact logging config? Did you use the package or from source?

Installing from source, I get the following error with the config below:

Error:
```
Error opening syslog:  Unix syslog delivery error
```

Config:
```
logging:
#  selectors: []
#
#  # Rotator config
  files:
#    path:
#    name:
#    rotateEveryBytes:
#    keepFiles:
#  to_syslog: false
  to_files: true
```
